### ISSUE TITLE
[i8n-ja] Translating docs to Japanese

### ISSUE THREAD

**Issue by YasunaCoffee** [huggingface/diffusers#6309]
Hi! I'm Yasuna🤗

Let's bring the documentation to all the Japanese-speaking community 🌐.

Who would want to translate? Please follow the 🤗 [TRANSLATING guide](https://github.com/huggingface/diffusers/blob/main/docs/TRANSLATING.md). Here is a list of the files ready for translation. Let us know in this issue if you'd like to translate any, and we'll add your name to the list.

Some notes:

* Please translate using an informal tone (imagine you are talking with a friend about Diffusers 🤗).
* Please translate in a gender-neutral way.
* Add your translations to the folder called `<languageCode>` inside the [source folder](https://github.com/huggingface/diffusers/tree/main/docs/source).
* Register your translation in `<languageCode>/_toctree.yml`; please follow the order of the [English version](https://github.com/huggingface/diffusers/blob/main/docs/source/en/_toctree.yml).
* Once you're finished, open a pull request and tag this issue by including #issue-number in the description, where issue-number is the number of this issue. Please ping @stevhliu for review.
* 🙋 If you'd like others to help you with the translation, you can also post in the 🤗 [forums](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63).

* Please write here the name of the md file from the following items you'd like to start to be translated.
(ex. I'd like to start translating TECHNIQUES section/reusing_seeds.md from now!)

Pull Request Format
```
Related to #[issue's no.]

What is this PR about ?

I translated the following files to implified Japanese:

toctree.yml
index.md
installation.md
quick-start.md
git_vs_http.md
repository.md

What should you check ?

Grammar and orthograph
If my pull requests follows GitHub/open source contribution good practices (I am a beginner)
```

Thank you so much for your help! 🤗

# GET STARTED section
- [x] index.md @YasunaCoffee 
- [x] installation.md
- [x] quicktour.md
- [x] stable_diffusion.md

# TUTORIALS section
- [ ] autopipeline.md @YasunaCoffee 
- [ ] basic_training.md @YasunaCoffee 
- [ ] fast_diffusion.md @YasunaCoffee 
- [x] tutorial_overview.md @YasunaCoffee 
- [ ] using_peft_for_inference.md @YasunaCoffee 

# USING-DIFFUSERS section
## LOADING&HUB section
- [ ] loading_overview.md @Prgckwb 
- [ ] loading.md @Prgckwb 
- [ ] schedulers.md @Prgckwb 
- [ ] custom_pipeline_overview.md @Prgckwb 
- [ ] using_safetensors.md @Prgckwb 
- [ ] other-formats.md @Prgckwb 
- [ ] loading_adapters.md @Prgckwb 
- [ ] push_to_hub.md @Prgckwb 

## TASKS section
- [ ] pipeline_overview.md
- [ ] unconditional_image_generation.md
- [ ] conditional_image_generation.md
- [ ] img2img.md
- [ ] inpaint.md
- [ ] depth2img.md

## TECHNIQUES section
- [ ] textual_inversion_inference.md
- [ ] reusing_seeds.md
- [ ] control_brightness.md
- [ ] weighted_prompts.md
- [ ] freeu.md

# USING DIFFUSERS (SPECIFIC PIPELINE EXAMPLES) section
- [ ] sdxl.md [Stable Diffusion XL](https://huggingface.co/docs/diffusers/using-diffusers/sdxl)
- [ ] sdxl_turbo.md [SDXL Turbo](https://huggingface.co/docs/diffusers/using-diffusers/sdxl_turbo)
- [ ] kandinsky.md [Kandinsky](https://huggingface.co/docs/diffusers/using-diffusers/kandinsky)
- [ ] controlnet.md [ControlNet](https://huggingface.co/docs/diffusers/using-diffusers/controlnet)
- [ ] shap-e.md [Shap-E](https://huggingface.co/docs/diffusers/using-diffusers/shap-e)
- [ ] diffedit.md [DiffEdit](https://huggingface.co/docs/diffusers/using-diffusers/diffedit)
- [ ] distilled_sd.md [Distilled Stable Diffusion inference](https://huggingface.co/docs/diffusers/using-diffusers/distilled_sd)
- [ ] callback.md [Pipeline callbacks](https://huggingface.co/docs/diffusers/using-diffusers/callback)
- [ ] reproducibility.md [Create reproducible pipelines](https://huggingface.co/docs/diffusers/using-diffusers/reproducibility)
- [ ] custom_pipeline_examples.md [Community pipelines](https://huggingface.co/docs/diffusers/using-diffusers/custom_pipeline_examples)
- [ ] contribute_pipeline.md [Contribute a community pipeline](https://huggingface.co/docs/diffusers/using-diffusers/contribute_pipeline)
- [ ] inference_with_lcm_lora.md [Latent Consistency Model-LoRA](https://huggingface.co/docs/diffusers/using-diffusers/inference_with_lcm_lora)
- [ ] inference_with_lcm.md [Latent Consistency Model](https://huggingface.co/docs/diffusers/using-diffusers/inference_with_lcm)
- [ ] svd.md [Stable Video Diffusion](https://huggingface.co/docs/diffusers/using-diffusers/svd)

# TRAINING section
- [ ] overview.md [Overview](https://huggingface.co/docs/diffusers/training/overview)
- [ ] create_dataset.md [Create a dataset for training](https://huggingface.co/docs/diffusers/training/create_dataset)
- [ ] adapt_a_model.md[Adapt a model to a new task](https://huggingface.co/docs/diffusers/training/adapt_a_model)

## MODELS
- [ ] unconditional_training.md[Unconditional image generation](https://huggingface.co/docs/diffusers/training/unconditional_training)
- [ ] text2image.md[Text-to-image](https://huggingface.co/docs/diffusers/training/text2image)
- [ ] sdxl.md[Stable Diffusion XL](https://huggingface.co/docs/diffusers/training/sdxl)
- [ ] kandinsky.md[Kandinsky 2.2](https://huggingface.co/docs/diffusers/training/kandinsky)
- [ ] wuerstchen[Wuerstchen](https://huggingface.co/docs/diffusers/training/wuerstchen)
- [ ] controlnet.md[ControlNet](https://huggingface.co/docs/diffusers/training/controlnet)
- [ ] t2i_adapters.md[T2I-Adapters](https://huggingface.co/docs/diffusers/training/t2i_adapters)
- [ ] instructpix2pix.md[InstructPix2Pix](https://huggingface.co/docs/diffusers/training/instructpix2pix)

## METHODS
- [ ] text_inversion.md[Textual Inversion](https://huggingface.co/docs/diffusers/training/text_inversion)
- [ ] dreambooth.md[DreamBooth](https://huggingface.co/docs/diffusers/training/dreambooth)
- [ ] lora.md[LoRA](https://huggingface.co/docs/diffusers/training/lora)
- [ ] custom_diffusion.md[Custom Diffusion](https://huggingface.co/docs/diffusers/training/custom_diffusion)
- [ ] lcm_distill.md[Latent Consistency Distillation](https://huggingface.co/docs/diffusers/training/lcm_distill)
- [ ] ddpo.md[Reinforcement learning training with DDPO](https://huggingface.co/docs/diffusers/training/ddpo)

## TAKING DIFFUSERS BEYOND IMAGES
- [ ] using-diffusers/other-modalities.md [Other Modalities](https://huggingface.co/docs/diffusers/using-diffusers/other-modalities)

# OPTIMIZATION section
- [ ] opt_overview.md[Overview](https://huggingface.co/docs/diffusers/optimization/opt_overview)

## GENERAL OPTIMIZATIONS
- [ ] fp16.md[Speed up inference](https://huggingface.co/docs/diffusers/optimization/fp16)
- [ ] memory.md[Reduce memory usage](https://huggingface.co/docs/diffusers/optimization/memory)
- [ ] torch2.0.md[PyTorch 2.0](https://huggingface.co/docs/diffusers/optimization/torch2.0)
- [ ] xformers.md[xFormers](https://huggingface.co/docs/diffusers/optimization/xformers)
- [ ] tome.md[Token merging](https://huggingface.co/docs/diffusers/optimization/tome)

## OPTIMIZED MODEL TYPES
- [ ] stable_diffusion_jax_how_to.md [JAX/Flax](https://huggingface.co/docs/diffusers/using-diffusers/stable_diffusion_jax_how_to)
- [ ] onnx.md[ONNX](https://huggingface.co/docs/diffusers/optimization/onnx)
- [ ] open_vino.md[OpenVINO](https://huggingface.co/docs/diffusers/optimization/open_vino)
- [ ] coreml.md[Core ML](https://huggingface.co/docs/diffusers/optimization/coreml)

## OPTIMIZED HARDWARE
- [ ] mps.md[Metal Performance Shaders (MPS)](https://huggingface.co/docs/diffusers/optimization/mps)
- [ ] habana.md[Habana Gaudi](https://huggingface.co/docs/diffusers/optimization/habana)

## CONCEPTUAL GUIDES
- [ ] conceptual/philosophy.md[Philosophy](https://huggingface.co/docs/diffusers/conceptual/philosophy)
- [ ] using-diffusers/controlling_generation.md[Controlled generation](https://huggingface.co/docs/diffusers/using-diffusers/controlling_generation)
- [ ] conceptual/contribution.md[How to contribute?](https://huggingface.co/docs/diffusers/conceptual/contribution)
- [ ] conceptual/ethical_guidelines.md[Diffusers' Ethical Guidelines](https://huggingface.co/docs/diffusers/conceptual/ethical_guidelines)
- [ ] conceptual/evaluation.md[Evaluating Diffusion Models](https://huggingface.co/docs/diffusers/conceptual/evaluation)

**Comment by YasunaCoffee** [comment]
- I am now going to write a **[tutorial for differs](https://huggingface.co/docs/diffusers/tutorials/tutorial_overview)**

**Comment by sayakpaul** [comment]
CC: @stevhliu

**Comment by stevhliu** [comment]
Thanks for continuing the efforts to translate the docs to Japanese! 🎉 

To make it easier for contributors to see what has been translated already and what still needs to be translated, can you edit and update your issue to look like this one [here](https://github.com/huggingface/huggingface_hub/issues/1915#issue-2044469039)?

**Comment by Prgckwb** [comment]
Hello, everydiffuser 🤗 

I'll try to translate LOADING&HUB section from now!

**Comment by Prgckwb** [comment]
I have finished translating:
- docs/source/ja/using-diffusers/loading_overview.md
- docs/source/ja/using-diffusers/loading.md

Next, I will tackle:
- docs/source/ja/using-diffusers/schedulers.md
- docs/source/ja/using-diffusers/custom_pipeline_overview.md
- docs/source/ja/using-diffusers/using_safetensors.md
