### ISSUE TITLE
[Tracker] modularize inferencing during and after training in the example scripts

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#6545]
We provide support for running validation inference during and after training in our officially maintained training examples. This is very helpful to keep track of the training progress. 

We could modularize some bits in the example to reduce the LoC. 

The `train_lcm_distill_lora_sdxl.py` [script](https://github.com/huggingface/diffusers/blob/main/examples/consistency_distillation/train_lcm_distill_lora_sdxl.py) already does this:

https://github.com/huggingface/diffusers/blob/33d2b5b08764d2579dd4ea555821b8986cd2dcf9/examples/consistency_distillation/train_lcm_distill_lora_sdxl.py#L100

It would be nice to follow something similar for the rest of the scripts too. Here's a handy list of the scripts where we'd like to incorporate this change:

- DreamBooth
  - [x] [SD LoRA](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py)
  - [x] [SDXL LoRA](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sdxl.py)
- InstructPix2Pix
  - [ ] [SD](https://github.com/huggingface/diffusers/blob/main/examples/instruct_pix2pix/train_instruct_pix2pix.py)
  - [x] [SDXL](https://github.com/huggingface/diffusers/blob/main/examples/instruct_pix2pix/train_instruct_pix2pix_sdxl.py)
- Text-to-image
  - [ ] [SD](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py)
  - [x] [SD LoRA](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py)
  - [x] [SDXL LoRA](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora_sdxl.py)

Feel free to comment here if you're interested. 

Also, when opening PRs, please target one example at a time and please tag me in the PRs.

**Comment by charchit7** [comment]
Hey @sayakpaul for text-to-image, [SD](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py)
`log-validation` is present : https://github.com/huggingface/diffusers/blob/33d2b5b08764d2579dd4ea555821b8986cd2dcf9/examples/text_to_image/train_text_to_image.py#L141

haven't gone through the code though if we need to modify something there.

**Comment by sayakpaul** [comment]
Ideally, this should be delegated to `log_validation()` too: 
https://github.com/huggingface/diffusers/blob/33d2b5b08764d2579dd4ea555821b8986cd2dcf9/examples/text_to_image/train_text_to_image.py#L1047

As done in `train_lcm_distill_lora_sdxl.py`.

**Comment by charchit7** [comment]
Got it. @sayakpaul I missed that part. Thanks!

**Comment by sang-k** [comment]
Hey @sayakpaul, @charchit7 
I'm interested in incorporating the change to InstructPix2Pix SD

**Comment by coolyashas** [comment]
> Hey @sayakpaul, @charchit7 I'm interested in incorporating the change to InstructPix2Pix SD

Hey @sang-k, I have been looking into InstructPix2Pix SD too.

**Comment by sang-k** [comment]
@coolyashas 
Oh, I see.
I will look into InstructPix2Pix SDXL then!

**Comment by coolyashas** [comment]
Working on InstructPix2Pix SD

**Comment by ParagEkbote** [comment]
Has this issue been resolved or are there any pending scripts I could contribute to modularize?

cc: @sayakpaul

**Comment by sayakpaul** [comment]
Yeah I think this can be closed now :)
