### ISSUE TITLE
[Tracker] use micro-conditioning for the SDXL trainers

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#6586]
SDXL makes use of micro-conditioning, and it does have quite a bit of an effect on the end results. For more details, refer to the paper [here](https://arxiv.org/abs/2307.01952). 

Currently, not all of our SDXL trainers don't make use of micro-conditioning. So, it'd be nice to have micro-conditioning support as in https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora_sdxl.py. 

Below is a list of the training scripts where we'd like to have this change incorporated: 

- [ ] [DreamBooth SDXL LoRA](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sdxl.py)
- [ ] [SDXL LCM-LoRA](https://github.com/huggingface/diffusers/blob/main/examples/consistency_distillation/train_lcm_distill_lora_sdxl.py) (it needs to be slightly refactored as done in https://github.com/huggingface/diffusers/pull/6547 by @haofanwang)
- [ ] [ControlNet SDXL](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet_sdxl.py)
- [ ] [T2I Adapter SDXL](https://github.com/huggingface/diffusers/blob/main/examples/t2i_adapter/train_t2i_adapter_sdxl.py)
- [ ] [Textual inversion SDXL](https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion_sdxl.py) (same as what's mentioned for SDXL LCM-LoRA above)

Feel free to open PRs targeting only ONE example at a time and tag me. Please also share an example training command while submitting the PRs. The command doesn't have to run the training for a large number of steps. Anything in the range of [4, 10] should suffice.

**Comment by sayakpaul** [comment]
@jiqing-feng, would you like to take [Textual inversion SDXL](https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion_sdxl.py)?

@linoytsaban would you like to take [Advanced SDXL trainer](https://github.com/huggingface/diffusers/blob/main/examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py)?

**Comment by sayakpaul** [comment]
DreamBooth SDXL LoRA should run in Colab. Refer to the associated readme for more details.

**Comment by linoytsaban** [comment]
> @linoytsaban would you like to take [Advanced SDXL trainer](https://github.com/huggingface/diffusers/blob/main/examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py)?

sure!

**Comment by jiqing-feng** [comment]
> @jiqing-feng, would you like to take [Textual inversion SDXL](https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion_sdxl.py)?
> 
> @linoytsaban would you like to take [Advanced SDXL trainer](https://github.com/huggingface/diffusers/blob/main/examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py)?

Sorry for the delay, I have been quite busy recently; I will do it once I have time.

**Comment by ChengsongLu** [comment]
> DreamBooth SDXL LoRA should run in Colab. Refer to the associated readme for more details.

Can't it run locally?

**Comment by sayakpaul** [comment]
You need to repurpose the code accordingly for that.

**Comment by cosmo3769** [comment]
Hello @sayakpaul, I would love to work on [ControlNet SDXL](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet_sdxl.py). Thank you.

**Comment by sayakpaul** [comment]
Please go ahead.

**Comment by jiqing-feng** [comment]
Hi @sayakpaul . I think the micro conditioning is already in the example, see [conditioning_image_size](https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion_sdxl.py#L547) and [conditioning_crop_size](https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion_sdxl.py#L557), and they are all in the [add_time_ids](https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion_sdxl.py#L902-L906). 

BTW, I found a minor error that I resize the image after crop, and already fixed it in #7095

**Comment by sayakpaul** [comment]
You are right. Thanks for the quick fix.

**Comment by ViktoriiaRomanova** [comment]
Hi @sayakpaul, I’d like to take on the task of adding micro-conditioning support to the [T2I Adapter SDXL trainer](https://github.com/huggingface/diffusers/blob/main/examples/t2i_adapter/train_t2i_adapter_sdxl.py). I’ll follow the established implementation in train_text_to_image_lora_sdxl.py. Is this task still available, and may I proceed? Thanks!
