### ISSUE TITLE
[Tracker] use the new model card utilities for saving model cards from the training script

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#6891]
With https://github.com/huggingface/diffusers/pull/6729, we shifted to a more resilient and robust way to generate model cards from the DreamBooth training scripts. 

So, we're keen for the community to help us do this for the other training scripts that save model cards:

- [x] [T2I](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py)
- [x] [T2I LoRA](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py)
- [x] [T2I SDXL](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py)
- [x] [T2I SDXL LoRA](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora_sdxl.py)
- [x] [ControlNet](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py)
- [x] [ControlNet SDXL](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet_sdxl.py)
- [x] [T2I Adapter SDXL](https://github.com/huggingface/diffusers/blob/main/examples/t2i_adapter/train_t2i_adapter_sdxl.py)
- [x] [Textual inversion](https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion.py)
- [x] [Textual inversion SDXL](https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion_sdxl.py)
- [ ] [Advanced diffusion training](https://github.com/huggingface/diffusers/blob/main/examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py) (cc: @linoytsaban)
- [ ] [Advanced diffusion training SDXL](https://github.com/huggingface/diffusers/blob/main/examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py) (cc: @linoytsaban)

While creating PRs, please also supply a notebook that generates the model card for a respective example. An example is available here: https://github.com/huggingface/diffusers/pull/6729#issue-2103496495. Use https://github.com/huggingface/diffusers/pull/6729 as a reference (only refer to the changes made in the training scripts). Please also target ONLY ONE example at a time in your PRs. 

Please also tag me for a review when you open the PRs.

**Comment by standardAI** [comment]
Hi Sayak! I would like to take Textual Inversion.

**Comment by sayakpaul** [comment]
All yours!

**Comment by bamps53** [comment]
Hi @sayakpaul, I checked #6729 and attempted to run your test notebook (https://huggingface.co/sayakpaul/test-model-card-template-dreambooth/blob/main/test_dreambooth_model_card.ipynb). However, it appears to not work for #6729 as it uses the `instance_prompt` keyword arguments in `load_or_create_model_card`. Changing it to `prompt` seems to fix the issue. My question is about the maintenance of these notebooks. Is it acceptable to create a notebook solely to verify that my PR is working at the time?

**Comment by bamps53** [comment]
Oh, it seems not only notebooks, but also training scripts in examples are not workings now.
I made PR #6895 to fix these before this issue.

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul, I would love to work on this issue. I read the #6729 and based on my understanding what we have to do is - 
1. We need to add a training script for these models where we append the changes you mentioned in #6729. Basically all those changes that you made to this file `examples/dreambooth/train_dreambooth_lora.py`
1. We need to use your notebook and generate model_cards for different models as well right?

**Comment by Bhavay-2001** [comment]
If this is the case then I would be happy to work on ControlNet and ControlNetSDXL.

**Comment by sayakpaul** [comment]
@bamps53 I have fixed the example notebook to clear the errors. So, that should be fine. Have reviewed your PR: https://github.com/huggingface/diffusers/pull/6895 as well. It looks solid. 

I have also updated the description of this issue, clearly mentioning that contributors should open one PR at a time, targeting only one example. Hope that helps.

**Comment by sayakpaul** [comment]
@Bhavay-2001 I don't think you need to add any training script. We need to make use of the utilities (as shown in my example notebook and also in the [PR](https://github.com/huggingface/diffusers/pull/6729)) to create the model cards of the examples I have listed in the description. Is it more clear?

**Comment by bamps53** [comment]
@sayakpaul 
Thanks, I got it!
I'll split the PR for each.

**Comment by bamps53** [comment]
Sorry for the mess, but I created 3 PRs for each controlnet training scripts!
#6908
#6909
#6910

By the way it was more tadious to create notebooks than modifying code itself... Any better way?

**Comment by sayakpaul** [comment]
I think you misunderstood the description. The PR should target the actual training script. I asked for a notebook example to be able to quickly verify if the changes lead to expected README. The notebook can be a part of the PR description but not a part of the PR changes. 

Not sure how I can convey this more thoroughly.

**Comment by cosmo3769** [comment]
Hello @sayakpaul, I would love to work on all the T2I ones. Thank you!

**Comment by sayakpaul** [comment]
Yes, feel free to!

**Comment by chiral-carbon** [comment]
hi @sayakpaul could I claim Advanced Diffusion Training and Advanced Diffusion SDXL?

**Comment by Stepheni12** [comment]
I'll take Textual Inversion SDXL if it's available!

**Comment by sayakpaul** [comment]
@chiral-carbon, @Stepheni12 feel free to proceed :)

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul, I have also some pending PRs from a previous issue #6585. Can you please check them as well?

**Comment by chiral-carbon** [comment]
Hi sorry, I’m going to push a PR by the end of the week and was delayed due to some heavy backlog in my work, sorry about it.

**Comment by chiral-carbon** [comment]
Hi @sayakpaul sorry for the delay! I have opened 2 new PRs for the tasks I had picked up.

**Comment by a-r-r-o-w** [comment]
@sayakpaul Can we close? Or should we remove the stale label?

**Comment by sayakpaul** [comment]
I think it's okay to close.

**Comment by chiral-carbon** [comment]
@sayakpaul @a-r-r-o-w @linoytsaban should I close the PRs I had made? they haven't been reviewed since I had last made commits to address comments 😅

**Comment by a-r-r-o-w** [comment]
Oh sorry, no need to close them! I've requested reviews from Linoy - we should be able to merge them soon if we get an approved review
